### PR TITLE
Updated weather features as suggested by tutors,

### PR DESCRIPTION
**Pull request by semioniy**
weather chunked in S2 cells (level 11) and timeframes of 2 hours
for 500 entries method became 3,6 times faster

### CODE REVIEW

**Comment by semioniy** [comment]
for some reason weather server returns more and more incomplete request answers.
this is not because of newer version of the script, it is so on the older ones as well.

**Comment by gyachdav** [comment]
What is the source?

**Comment by semioniy** [comment]
forecast.io

**Comment by semioniy** [comment]
maybe with all these repeating requests I accidentally DDoSed the API)
It is not that funny though, because API returns now even more bad request responses than before....

**Comment by semioniy** [comment]
@gyachdav in the last run I got 80 normal server answers and 303 bad answers (one of the answer fields, eg temperature/pressure was missing)
What should I do?

**Comment by gyachdav** [comment]
Any idea why you're getting bad responses? The only thing to do here is to investigate and figure out whats the source for missing information. Would be useful if you post some request and responses here that we can try it out.

**Comment by sacdallago** [comment]
Are you using API keys? In case, try to get yourself new ones!

If you are trying this from a home connection, try to go to http://www.ip-adress.com , note your ip, reboot the router, see if the ip changes (usually home connections are dynamic).

If you are behind the LRZ network it's bad because the entire network exists with a set of 9 IPs (if I'm not mistaken) and they are bound to physical zones, so there's no way to circumnavigate this except for using proxies or VPNs. You can try with a free VPN or proxy, though VPNs are usually banned by API services as big as forecast.io. Tor can also be a solution in this case, but you better do it in a VM :D

**Comment by semioniy** [comment]
@sacdallago I'm using API keys, but they are not the problem. With new key I get the same bad responses, as well as from other IPs.
It seems to me that the server I send requests to has corrupted/ not full database.
But I tried to use actual weather till now. if it is ok to use weather forecast for that day, I'll use it, because almost in every case when actual weather is missing, the forecast is still there.

**Comment by goldbergtatyana** [comment]
There is no problem in using the weather forecast. It is a very good idea actualy, @semioniy !

**Comment by semioniy** [comment]
Good, that'll do then)

**Pull request closed without merging**
