### PR TITLE
Feature/population

### PR DESCRIPTION
**Pull request by marwage**
The script gives you for a given latitude and longitude the city/town/village with nominatim.openstreetmap.org
and for that place the population based on WolframAlpha
Would be nice if you look over the code ;)
#28

### CODE REVIEW

**Comment by bensLine** [comment]
Cool, just tested the script! Unfortunately, it takes veeery long to get the population. the call to openstreet map for the city name is way faster.

If we want to use the data the script needs to be implemented as feature source. However, we are mainly interested in the population, but if it takes that long I'm not sure if that feature will be applicable :/ 
Seems like wolframalpha is here the problem as the requests take a very long time. I guess we need to find another source if we cannot speed up the requests to wolframalpha.

**Comment by goldbergtatyana** [comment]
Please ask the https://github.com/PokemonGoers/PokeData group if the ran into the same issue and how they resolved it.

**Comment by bensLine** [comment]
@goldbergtatyana I googled a little bit and the problem seems to be a general one of wolfram alpha. at least for the free version the response time is very slow - also on their website e.g. https://www.wolframalpha.com/input/?i=munich

**Comment by goldbergtatyana** [comment]
@sacdallago @gyachdav do you know if we have an elegant solution for this issue?

**Comment by gyachdav** [comment]
hmm if wolfram alpha is slow then we will indeed need a different source. How's Wikipedia in thatvregard?

**Comment by sacdallago** [comment]
I like @gyachdav 's idea.. If we know the city name, we might just check with wiki the population density.

Otherwise: how does wolfram alpha _actually_ do it? Is there someway we can completely mine their databases? Would it be possible to get some YxY patches with population density and then just go by nearest neighbor?

**Pull request merged**
