### PR TITLE
parses latitude and longitude to an address

### PR DESCRIPTION
**Pull request by marwage**
I build a function that returns the address of the given latitude and longitude
Maybe it's helpful for getting the population.

### CODE REVIEW

**Comment by sacdallago** [comment]
Nice! Reverse geo-coding it's called :) this thing is awesome, I implemented this thing so many times :D

**Comment by bensLine** [comment]
nice one! That will be for sure helpful :)

**Comment by sacdallago** [comment]
Remember to delete merged branches ;)

**Comment by jonas-he** [comment]
@marwage @sacdallago since we are also working on features i wanted to ask if our server/backend should compute them (see https://github.com/PokemonGoers/PokeData/issues/130) or if the machine learners should compute it themselves ? If the former is the case i would kindly ask to use your code.
However I think theres a limit for Google API, see https://developers.google.com/maps/documentation/geocoding/usage-limits?hl=de

**Comment by bensLine** [comment]
@jonas-he concerning the limitation, I guess we'll batch process the API data once to create our ML data set. Maybe we have to wait in between the batches but since this process actually has only to be performed once it should not be a problem, @goldbergtatyana ?!

**Comment by goldbergtatyana** [comment]
When a user opens the app then the features describing the location (long, lat, terrain, weather, etc.) will need to be fetched from the web - they are not pre-computed and not stored in our databases.

**Comment by bensLine** [comment]
@goldbergtatyana, right! How should we deal with the limitations of APIs? e.g. only 2500 requests per day or similar

**Comment by goldbergtatyana** [comment]
@sacdallago @gyachdav

**Comment by sacdallago** [comment]
I see the point @goldbergtatyana 
First: let's see which features are necessary, then discuss with @PokemonGoers/catch-em-all to see where to get the data from on the spot for a connecting user (location is easy, weather is easy, terrain might be easy, given prior knowledge --> If the guys from the predictions get the data from somewhere, we just copy that data and reuse)

@bensLine you are referring to a different thing: you speak about the model. Yes. The model is computed once (or every once in a while) and for you to create the model you need the training /testing/cross-testing data which will be the entire database. You should set up a programmatic solution to:
1. Get the data from the database given the database connection strings and collection name
2. Add relevant features (weather, terrain,..) to the data points via external services (for weather, aka variable information) or prior knowledge (you have a file-based database describing features of the world, population density,... aka static information)
3. Compute the model

**Pull request merged**
